### ISSUE TITLE
Not usable for me

### ISSUE THREAD

**Issue by ChiisanaKira** [montgomerysamantha/talkabot#1]
Every time i want to confirm my specified things in the login screen the program crashes! Is there a solution or is this error known? I really like the design of the program and would also like to use it xD

**Comment by montgomerysamantha** [comment]
Can you describe more about the issue, what are you inputting? I haven't run into this yet.

**Comment by montgomerysamantha** [comment]
[Fixed in PR](https://github.com/montgomerysamantha/talkabot/pull/5), thanks everyone for the help! 🫶
