### ISSUE TITLE
Crash on login

### ISSUE THREAD

**Issue by At0mC3** [montgomerysamantha/talkabot#4]
Here is an explanation about this issue #1 .

When the software is opened for the first time, a crash will happen right after confirming the oauth token and username.

The crash happens inside the function 'LoadCommands' at line 79 in `TalkaBot.xaml.cs`. The cause of the crash seems to be that obj.commandList is not initialized because the function `LoadConfig` called at line 75 seems to return nothing.

Here is the code from the `LoadConfig` function:

```
ConfigObject obj = new ConfigObject();

try
{
    using (FileStream fs = new FileStream("Config.xml", FileMode.Open, FileAccess.Read))
    {
        XmlSerializer xs = new XmlSerializer(typeof(ConfigObject));

        obj = (ConfigObject)xs.Deserialize(fs);
        foreach(Command cmd in obj.commandList)
        {
            cmd.cooldown = new TimeSpan(cmd.ticks);
        }
    }
}
catch(FileNotFoundException e)
{
    
}

return obj;
```

The Config.xml will not be present when first running the software which will cause the catch condition to be hit. Since the exception is not handled properly, an uninitialized object will be returned which will cause the crash in the function `LoadCommands`.

**Comment by At0mC3** [comment]
#5

**Comment by montgomerysamantha** [comment]
[Fixed in PR ](https://github.com/montgomerysamantha/talkabot/pull/5), thank you for the kind and thorough explanation.
